### 1.  Create a dictionary where each object contains a list of one float (Age) and one string (Family name) (at least 5 objects)
Example:
`{Charles: [23.4, "Darwin"], Alan: [42.5, "Turing"]}`

In [4]:
people_dict = {'Andrew':[20.4, 'Li'] ,
               'Bob':[15.5, 'Wang'], 
               'Cindy':[30.6, 'Zhou'], 
               'Roger':[40.8, 'Sun'], 
               'Hellen':[25.3,'Qian']}
people_dict

{'Andrew': [20.4, 'Li'],
 'Bob': [15.5, 'Wang'],
 'Cindy': [30.6, 'Zhou'],
 'Hellen': [25.3, 'Qian'],
 'Roger': [40.8, 'Sun']}

### 2. Delete one object from the dictionary

In [5]:
people_dict.pop('Cindy')

[30.6, 'Zhou']

In [6]:
people_dict

{'Andrew': [20.4, 'Li'],
 'Bob': [15.5, 'Wang'],
 'Hellen': [25.3, 'Qian'],
 'Roger': [40.8, 'Sun']}

In [8]:
del(people_dict['Bob'])

In [9]:
people_dict

{'Andrew': [20.4, 'Li'], 'Hellen': [25.3, 'Qian'], 'Roger': [40.8, 'Sun']}

### 3. Replace the float number of one of your objects - we are changing a list entry inside a dictionary record! look at Darwin's new age

Example:
`{Charles: [99.73, "Darwin"], Alan: [42.5, "Turing"]}`

In [31]:
people_dict['Bob'][0]=19
people_dict

{'Andrew': [20.4, 'Li'],
 'Bob': [19, 'Wang'],
 'Hellen': [25.3, 'Qian'],
 'Roger': [40.8, 'Sun']}

### 4. write a for loop that goes through all records in the dictionary, prints the family name and assigns the float numbers into one merged list (see ages)

`ages = [23.4, 22.9, 552.9]`

In [32]:
names = []
ages = []
for key, value in people_dict.items():
    ages.append(value[0])
    names.append(value[1])
print(names)
print(ages)

['Li', 'Qian', 'Sun', 'Wang']
[20.4, 25.3, 40.8, 19]


### 5. Download your notebbok as a .py (regular python script) save it somewhere you know

### 6. Go to terminal, navigate to the folder where you have saved the script and execute it through the terminal

`use commandds: 
cd and 
python your_script.py`

### [optional] Calculate with a for loop the median and mean of the ages list

**

In [33]:
ages

[20.4, 25.3, 40.8, 19]

- Age mean

In [34]:
age_sum = 0
for age in ages:
    age_sum += age        
age_mean = age_sum/len(ages)   
print(age_mean)

26.375


In [35]:
age_mean = sum(ages)/len(ages) 
print(age_mean)

26.375


**sort(list) vs list.sort()**
- list.sort() # sort in place
- sort(list) #does not sort the list in place, can assign to a new list

**sort(tuple)-> return a list**
**tuple.sort() -> won't work, since tuple is immutable**

In [36]:
ages.sort() #sort in place

In [37]:
ages

[19, 20.4, 25.3, 40.8]

In [38]:
n = len(ages)
n

4

In [49]:
from math import floor
floor(5/2)

2

In [48]:
medium = 0 
if n%2 ==0: 
    i = int(n/2)
    medium = (ages[i]+ages[i-1])/2
else:
    i = floor(n)
    medium = ages[i]
print(medium) 

22.85


In [1]:
import numpy as np

In [ ]:
np.random.rand(2,3)

In [3]:
np.random.randint(1,10)

array([[0.06528023, 0.46069227, 0.60398668],
       [0.60255176, 0.81411732, 0.76247161]])

In [19]:
np.random.random(10)

array([0.80045694, 0.13491249, 0.15700545, 0.47084129, 0.3299854 ,
       0.41210357, 0.22472979, 0.67518076, 0.67841185, 0.61147194])

In [18]:
np.random.normal(2,1,10)

array([0.7993687 , 3.23121986, 2.21193303, 0.94200599, 2.63671425,
       1.78317772, 3.61277072, 0.68161004, 4.92844812, 2.32188998])