# Pandas and numpy - pair-up
### Discussion session

1. How will you read the following data into a pandas data frame ? 
 ` ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt`

In [1]:
import numpy as np
import pandas as pd

In [2]:
url = 'ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt' #file link

In [3]:
cols = ['Year','Month','Date', 'average','interpolated','trend','days'] #col names

In [4]:
df=pd.read_csv(url,comment='#', delim_whitespace=True, names = cols) #load file

In [5]:
df.head(5) #check

Year  Month      Date  average  interpolated   trend  days
0  1958      3  1958.208   315.71        315.71  314.62    -1
1  1958      4  1958.292   317.45        317.45  315.29    -1
2  1958      5  1958.375   317.50        317.50  314.71    -1
3  1958      6  1958.458   -99.99        317.10  314.85    -1
4  1958      7  1958.542   315.86        315.86  314.98    -1

2. How would you pick columns 0,1,3 ?  
`[[0, 1, 3]]`

In [6]:
cols_sub =[df.columns[n] for n in(0,1,3)] #retrieve col list
cols_sub

['Year', 'Month', 'average']

In [7]:
df[cols_sub].head() #check

Year  Month  average
0  1958      3   315.71
1  1958      4   317.45
2  1958      5   317.50
3  1958      6   -99.99
4  1958      7   315.86

3. Use a for loop to find all rows where 
Co2 (column 3) enteries with the value -99.99 (these are missing values) and replace them with NaN values (try using np.nan - do you know what it is? )

In [8]:
mask = df['average'] == -99.99 #check 
df.loc[mask,'average']

3     -99.99
7     -99.99
71    -99.99
72    -99.99
73    -99.99
213   -99.99
313   -99.99
Name: average, dtype: float64

In [9]:
df['average'].replace(to_replace = -99.99, value = np.nan, inplace=True) #replace value

In [10]:
df.loc[mask,'average'] #check

3     NaN
7     NaN
71    NaN
72    NaN
73    NaN
213   NaN
313   NaN
Name: average, dtype: float64

4. Change names of columns to year, month, and CO2 (use colnames)

strip spaces of col names
```python
df.columns = df.columns.str.strip()
```

In [11]:
df.columns = ['Year','Month','Date', 'C02_average','interpolated','trend','days'] #update col names

In [12]:
df.head() #check

Year  Month      Date  C02_average  interpolated   trend  days
0  1958      3  1958.208       315.71        315.71  314.62    -1
1  1958      4  1958.292       317.45        317.45  315.29    -1
2  1958      5  1958.375       317.50        317.50  314.71    -1
3  1958      6  1958.458          NaN        317.10  314.85    -1
4  1958      7  1958.542       315.86        315.86  314.98    -1

5. Add a column 'Day' and specifiy the day 15 for all enteries

In [13]:
df.insert(len(df.columns),'Day',15) #insert col at the end

In [14]:
df.head() #check

Year  Month      Date  C02_average  interpolated   trend  days  Day
0  1958      3  1958.208       315.71        315.71  314.62    -1   15
1  1958      4  1958.292       317.45        317.45  315.29    -1   15
2  1958      5  1958.375       317.50        317.50  314.71    -1   15
3  1958      6  1958.458          NaN        317.10  314.85    -1   15
4  1958      7  1958.542       315.86        315.86  314.98    -1   15

6. Add a date column according to the 'year', 'month' and 'day' columns (options: use apply with lambda or for loop together with datetime.date (make sure to import it)) 

**? datetime.date ?**

```python
pd.to_datetime(df[['year', 'month', 'day', 'hour', 'minute']])
or 
pd.to_datetime(dict(year=df.Y, month=df.M, day=df.D))
#dtype: datetime64[ns]
#2015-02-04 02:10:00
```

In [15]:
from datetime import date

In [16]:
df.insert(len(df.columns),'date',pd.to_datetime(df[['Year','Month','Day']])) #add date col

In [17]:
print(df.head())

   Year  Month      Date  C02_average  interpolated   trend  days  Day  \
0  1958      3  1958.208       315.71        315.71  314.62    -1   15   
1  1958      4  1958.292       317.45        317.45  315.29    -1   15   
2  1958      5  1958.375       317.50        317.50  314.71    -1   15   
3  1958      6  1958.458          NaN        317.10  314.85    -1   15   
4  1958      7  1958.542       315.86        315.86  314.98    -1   15   

        date  
0 1958-03-15  
1 1958-04-15  
2 1958-05-15  
3 1958-06-15  
4 1958-07-15  


7. Drop the 'Day' column

In [18]:
df.drop(columns=['Day'], inplace=True) #drop col

In [19]:
df.head(10)

Year  Month      Date  C02_average  interpolated   trend  days       date
0  1958      3  1958.208       315.71        315.71  314.62    -1 1958-03-15
1  1958      4  1958.292       317.45        317.45  315.29    -1 1958-04-15
2  1958      5  1958.375       317.50        317.50  314.71    -1 1958-05-15
3  1958      6  1958.458          NaN        317.10  314.85    -1 1958-06-15
4  1958      7  1958.542       315.86        315.86  314.98    -1 1958-07-15
5  1958      8  1958.625       314.93        314.93  315.94    -1 1958-08-15
6  1958      9  1958.708       313.20        313.20  315.91    -1 1958-09-15
7  1958     10  1958.792          NaN        312.66  315.61    -1 1958-10-15
8  1958     11  1958.875       313.33        313.33  315.31    -1 1958-11-15
9  1958     12  1958.958       314.67        314.67  315.61    -1 1958-12-15

In [20]:
df.shape

(735, 8)

8. use pandas groupby to print the yeaerly avg. of co2 per year. 

In [21]:
print(df['C02_average'].groupby(df['Year']).mean())

Year
1958    315.331250
1959    315.974167
1960    316.907500
1961    317.637500
1962    318.450833
1963    318.994167
1964    319.204444
1965    320.044167
1966    321.383333
1967    322.157500
1968    323.045000
1969    324.624167
1970    325.680000
1971    326.320000
1972    327.453333
1973    329.676667
1974    330.185000
1975    331.162727
1976    332.038333
1977    333.831667
1978    335.403333
1979    336.841667
1980    338.751667
1981    340.105000
1982    341.447500
1983    343.054167
1984    344.451818
1985    346.116667
1986    347.420000
1987    349.194167
           ...    
1990    354.394167
1991    355.607500
1992    356.445833
1993    357.100000
1994    358.833333
1995    360.820000
1996    362.605833
1997    363.729167
1998    366.700000
1999    368.377500
2000    369.550000
2001    371.143333
2002    373.279167
2003    375.802500
2004    377.522500
2005    379.795833
2006    381.895833
2007    383.791667
2008    385.604167
2009    387.430000
2010    389.898333
2011   

9. Pick columns that you think could be used to build a model and store them in numpy array (Answer why do we do that?)

```python
# The "average" column contains the monthly mean CO2 mole fraction determined
# from daily averages.  The mole fraction of CO2, expressed as parts per million
# (ppm) is the number of molecules of CO2 in every one million molecules of dried
# air (water vapor removed). 

# CO2 expressed as a mole fraction in dry air, micromol/mol, abbreviated as ppm
#
#  (-99.99 missing data;  -1 no data for #daily means in month)

# The interpolated monthly mean is then the sum of the average seasonal cycle
# value and the trend value for the missing month.
    # seasonal: compute for each month the average seasonal cycle in a 7-year window around each monthly value
    # trend: by removing the seasonal cycle, linearly interpolated for missing months
```

**Q? Depends what is the goal of the analysis? Not sure**

Pick col ['Year', 'Month', 'C02_average'] for now

In [22]:
col_arr = ['Year', 'Month', 'C02_average']
arr = df[col_arr].values
arr

array([[1958.  ,    3.  ,  315.71],
       [1958.  ,    4.  ,  317.45],
       [1958.  ,    5.  ,  317.5 ],
       ...,
       [2019.  ,    3.  ,  411.97],
       [2019.  ,    4.  ,  413.32],
       [2019.  ,    5.  ,  414.66]])

10. repeat step (3) but this time using the np.where command. 
```python
# Intuitively, np.where is like asking "tell me where in this array, entries satisfy a given condition".
a = np.arange(5,10)
np.where(a < 8)       # tell me where in a, entries are < 8
Out[]: (array([0, 1, 2]),)       # answer: entries indexed by 0, 1, 2
a[np.where(a < 8)] 
Out[]: array([5, 6, 7])          # selects from a entries 0, 1, 2    
```

In [23]:
np.isnan(arr) #check

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [24]:
np.isnan(arr).any() #check

True

In [25]:
print(np.where(np.isnan(arr))) # return list of row index, list of col index, with nan values

(array([  3,   7,  71,  72,  73, 213, 313]), array([2, 2, 2, 2, 2, 2, 2]))


In [26]:
#does not work:  np.where(arr is np.nan)

In [27]:
arr[np.where(np.isnan(arr))]

array([nan, nan, nan, nan, nan, nan, nan])

```python
# If you have an ndarray named arr, you can replace all elements >255 with a value x as follows:
arr[arr > 255] = x
# test
In [1]: import numpy as np
In [2]: A = np.random.rand(500, 500)
In [3]: timeit A[A > 0.5] = 5
100 loops, best of 3: 7.59 ms per loop
```    

11. Download the notebook as .py script and run it from your terminal. 
12. Create a branch in github repository called warm_up_draft  
13. push the notebook with the name CO2 to your new branch on github.

### Create a function to split data into training data and testing data
##### When applying machine learning algorithms in a supervised learning scenario we want to have data to learn from and some data we have never seen before to test what we have learnt. 

### We have two tasks: 
- 	Choosing a condition to split the data on (e.g. we 	gonna choose the year 2010)
-  Split the features from the target we want to 	predict

### 3. Create the function
 - cond_df is an array of the column you want to condition your split on
 - the idea is to use np.where on the condition column to get the indices on which the full dataset will be split
 - once we have the indices we can use them on the full dataset to make the split. Notice: the indices of the conditioned column and the pandas df are one and the same.
 - X are all the features and Y should be the CO2 column - please split them before executing the function and assign them to X annd Y 
 
`def tr_te_split(X, Y, cond_df, cond):`

`cond_df could be an array of the year column`
							
`use np.where
`

In [28]:
cols_X = [col for col in df.columns if col is not 'C02_average'] # retrieve feature col names
cols_X

['Year', 'Month', 'Date', 'interpolated', 'trend', 'days', 'date']

In [32]:
X = df[cols_X].values # Split X(features) and y('C02_average')
y = df['C02_average'].values

In [49]:
cond_f = X[:,0] # Year col is the 1st col in np.array
cond = 2000

In [50]:
def tr_te_split(X, Y, cond_df, cond):
    cond_split = cond_f<cond
    X_tr = X[np.where(cond_split)]
    X_te = X[np.where(~cond_split)]
    y_tr = y[np.where(cond_split)]
    y_te = y[np.where(~cond_split)]   
    return (X_tr, y_tr, X_te, y_te)

In [51]:
X_tr, y_tr, X_te, y_te = tr_te_split(X, y, cond_f, cond)

In [56]:
X_tr.shape, y_tr.shape

((502, 7), (502,))

In [57]:
X_te.shape, y_te.shape

((233, 7), (233,))